import { PresetExercise } from '@/types';

/**
 * Comprehensive exercise database with all exercises from the 6-day split
 */
export const ALL_EXERCISES: PresetExercise[] = [
  // Chest
  { name: 'Flat DB Press', muscleGroup: 'chest', category: 'compound' },
  { name: 'Incline DB Press', muscleGroup: 'chest', category: 'compound' },
  { name: 'Decline DB Press', muscleGroup: 'chest', category: 'compound' },
  { name: 'Plate-Loaded Chest Press', muscleGroup: 'chest', category: 'compound' },
  { name: 'Incline Machine Press', muscleGroup: 'chest', category: 'compound' },
  { name: 'Machine Chest Press (neutral grip)', muscleGroup: 'chest', category: 'compound' },
  { name: 'Machine Press (slow tempo)', muscleGroup: 'chest', category: 'compound' },
  { name: 'Incline Smith / Machine Press', muscleGroup: 'chest', category: 'compound' },
  { name: 'Decline Press', muscleGroup: 'chest', category: 'compound' },
  { name: 'Cable Chest Fly (mid)', muscleGroup: 'chest', category: 'isolation' },
  { name: 'Cable Fly', muscleGroup: 'chest', category: 'isolation' },
  { name: 'Low Cable Fly', muscleGroup: 'chest', category: 'isolation' },
  { name: 'Low-to-High Cable Fly', muscleGroup: 'chest', category: 'isolation' },
  { name: 'High-to-Low Cable Fly', muscleGroup: 'chest', category: 'isolation' },
  { name: 'Single-Arm Cable Fly', muscleGroup: 'chest', category: 'isolation' },
  { name: 'Pec Deck', muscleGroup: 'chest', category: 'isolation' },
  { name: 'Push-Ups', muscleGroup: 'chest', category: 'compound' },
  { name: 'Deep Push-Ups', muscleGroup: 'chest', category: 'compound' },
  { name: 'Isometric Push-Up Hold', muscleGroup: 'chest', category: 'isolation' },

  // Triceps
  { name: 'Rope Pushdown', muscleGroup: 'triceps', category: 'isolation' },
  { name: 'Straight Bar Pushdown', muscleGroup: 'triceps', category: 'isolation' },
  { name: 'V-Bar Pushdown', muscleGroup: 'triceps', category: 'isolation' },
  { name: 'Reverse-Grip Pushdown', muscleGroup: 'triceps', category: 'isolation' },
  { name: 'Single-Arm Cable Pushdown', muscleGroup: 'triceps', category: 'isolation' },
  { name: 'Skull Crushers', muscleGroup: 'triceps', category: 'isolation' },
  { name: 'Overhead Cable Extension', muscleGroup: 'triceps', category: 'isolation' },
  { name: 'DB Overhead Extension', muscleGroup: 'triceps', category: 'isolation' },
  { name: 'Single-Arm Overhead Extension', muscleGroup: 'triceps', category: 'isolation' },
  { name: 'Cable Kickbacks', muscleGroup: 'triceps', category: 'isolation' },
  { name: 'DB Kickbacks', muscleGroup: 'triceps', category: 'isolation' },
  { name: 'Assisted Dips', muscleGroup: 'triceps', category: 'compound' },
  { name: 'Bench Dips', muscleGroup: 'triceps', category: 'compound' },
  { name: 'Close-Grip Chest Press', muscleGroup: 'triceps', category: 'compound' },
  { name: 'Close-Grip Press', muscleGroup: 'triceps', category: 'compound' },
  { name: 'Machine Triceps Press', muscleGroup: 'triceps', category: 'compound' },
  { name: 'Machine Press', muscleGroup: 'triceps', category: 'compound' },

  // Back
  { name: 'Wide-Grip Lat Pulldown', muscleGroup: 'back', category: 'compound' },
  { name: 'Wide-Grip Pulldown', muscleGroup: 'back', category: 'compound' },
  { name: 'Neutral-Grip Lat Pulldown', muscleGroup: 'back', category: 'compound' },
  { name: 'Close-Grip Pulldown', muscleGroup: 'back', category: 'compound' },
  { name: 'Plate-Loaded Row', muscleGroup: 'back', category: 'compound' },
  { name: 'Seated Cable Row', muscleGroup: 'back', category: 'compound' },
  { name: 'Close-Grip Cable Row', muscleGroup: 'back', category: 'compound' },
  { name: 'One-Arm DB Row', muscleGroup: 'back', category: 'compound' },
  { name: 'Chest-Supported Row', muscleGroup: 'back', category: 'compound' },
  { name: 'Machine Row', muscleGroup: 'back', category: 'compound' },
  { name: 'Isometric Hold Row', muscleGroup: 'back', category: 'isolation' },
  { name: 'Straight-Arm Pulldown', muscleGroup: 'back', category: 'isolation' },
  { name: 'Cable Pullover', muscleGroup: 'back', category: 'isolation' },
  { name: 'Dead Hang', muscleGroup: 'back', category: 'isolation' },
  { name: 'Bar Hang Hold', muscleGroup: 'back', category: 'isolation' },
  { name: 'Towel Pull-Ups / Holds', muscleGroup: 'back', category: 'compound' },
  { name: 'Back Extension', muscleGroup: 'back', category: 'isolation' },

  // Biceps & Forearms
  { name: 'EZ-Bar Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Reverse EZ-Bar Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Incline DB Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Hammer Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Cross-Body Hammer Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Cable Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Straight Bar Cable Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Bayesian Cable Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Cable Wrist Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Preacher Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Spider Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Concentration Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Machine Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Isometric Curl Hold', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Wrist Curls', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Reverse Wrist Curls', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Behind-Back Wrist Curl', muscleGroup: 'biceps', category: 'isolation' },
  { name: 'Wrist Roller', muscleGroup: 'biceps', category: 'isolation' },

  // Shoulders
  { name: 'Shoulder Press Machine', muscleGroup: 'shoulders', category: 'compound' },
  { name: 'DB Shoulder Press', muscleGroup: 'shoulders', category: 'compound' },
  { name: 'Arnold Press', muscleGroup: 'shoulders', category: 'compound' },
  { name: 'Machine Shoulder Press (different grip)', muscleGroup: 'shoulders', category: 'compound' },
  { name: 'DB Lateral Raise', muscleGroup: 'shoulders', category: 'isolation' },
  { name: 'Cable Lateral Raise', muscleGroup: 'shoulders', category: 'isolation' },
  { name: 'Lean-Away Lateral Raise', muscleGroup: 'shoulders', category: 'isolation' },
  { name: 'Single-Arm Cable Lateral', muscleGroup: 'shoulders', category: 'isolation' },
  { name: 'Rear Delt Fly', muscleGroup: 'shoulders', category: 'isolation' },
  { name: 'Reverse Pec Deck', muscleGroup: 'shoulders', category: 'isolation' },
  { name: 'Face Pulls', muscleGroup: 'shoulders', category: 'isolation' },
  { name: 'Upright Cable Row (light)', muscleGroup: 'shoulders', category: 'compound' },

  // Legs
  { name: 'Squats / Leg Press', muscleGroup: 'legs', category: 'compound' },
  { name: 'Hack Squat / Narrow Leg Press', muscleGroup: 'legs', category: 'compound' },
  { name: 'Walking Lunges', muscleGroup: 'legs', category: 'compound' },
  { name: 'Reverse Lunges', muscleGroup: 'legs', category: 'compound' },
  { name: 'Leg Extension', muscleGroup: 'quads', category: 'isolation' },
  { name: 'Sissy Squat / Heels-Elevated Squat', muscleGroup: 'quads', category: 'compound' },
  { name: 'Romanian Deadlift', muscleGroup: 'hamstrings', category: 'compound' },
  { name: 'Stiff-Leg Deadlift', muscleGroup: 'hamstrings', category: 'compound' },
  { name: 'Seated Leg Curl', muscleGroup: 'hamstrings', category: 'isolation' },
  { name: 'Lying Leg Curl', muscleGroup: 'hamstrings', category: 'isolation' },
  { name: 'Standing Calf Raise', muscleGroup: 'calves', category: 'isolation' },
  { name: 'Seated Calf Raise', muscleGroup: 'calves', category: 'isolation' },

  // Abs & Core
  { name: 'Hanging Leg Raises', muscleGroup: 'abs', category: 'compound' },
  { name: 'Hanging Leg Raise', muscleGroup: 'abs', category: 'compound' },
  { name: 'Hanging Knee Raises', muscleGroup: 'abs', category: 'compound' },
  { name: 'Toes-to-Bar / High Leg Raise', muscleGroup: 'abs', category: 'compound' },
  { name: 'Cable Crunch', muscleGroup: 'abs', category: 'isolation' },
  { name: 'Weighted Crunch', muscleGroup: 'abs', category: 'isolation' },
  { name: 'Decline Crunch', muscleGroup: 'abs', category: 'isolation' },
  { name: 'Decline Sit-Ups', muscleGroup: 'abs', category: 'compound' },
  { name: 'Reverse Crunch', muscleGroup: 'abs', category: 'isolation' },
  { name: 'V-Ups', muscleGroup: 'abs', category: 'compound' },
  { name: 'Bicycle Crunch', muscleGroup: 'abs', category: 'isolation' },
  { name: 'Cable Oblique Crunch', muscleGroup: 'abs', category: 'isolation' },
  { name: 'Russian Twists', muscleGroup: 'abs', category: 'isolation' },
  { name: 'Cable Woodchopper', muscleGroup: 'abs', category: 'compound' },
  { name: 'Plank', muscleGroup: 'core', category: 'isolation' },
  { name: 'Long Plank Hold', muscleGroup: 'core', category: 'isolation' },
  { name: 'Side Plank', muscleGroup: 'core', category: 'isolation' },
  { name: 'Hollow Body Hold', muscleGroup: 'core', category: 'isolation' },

  // Full Body / Functional
  { name: "Farmer's Walk", muscleGroup: 'full-body', category: 'compound' },
  { name: 'Timed Farmer Walk', muscleGroup: 'full-body', category: 'compound' },
  { name: 'Plate Pinch Hold', muscleGroup: 'full-body', category: 'isolation' },
  { name: 'Fat-Grip Holds', muscleGroup: 'full-body', category: 'isolation' },
];

export const MUSCLE_GROUPS = [
  'chest',
  'back',
  'shoulders',
  'biceps',
  'triceps',
  'legs',
  'quads',
  'hamstrings',
  'glutes',
  'calves',
  'abs',
  'core',
  'full-body',
] as const;

export const MUSCLE_GROUP_LABELS: Record<string, string> = {
  chest: 'Chest',
  back: 'Back',
  shoulders: 'Shoulders',
  biceps: 'Biceps',
  triceps: 'Triceps',
  legs: 'Legs',
  quads: 'Quadriceps',
  hamstrings: 'Hamstrings',
  glutes: 'Glutes',
  calves: 'Calves',
  abs: 'Abs',
  core: 'Core',
  'full-body': 'Full Body',
};
